# Generated by Django 5.0.1 on 2024-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_user_favorite_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(default=500000000),
        ),
    ]
