# Generated by Django 4.2.7 on 2024-01-30 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_georgian_alphabet', message='მიუთითეთ მხოლოდ ქართული ასოები', regex='^[ა-ჰ\\s]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='არაა მითითებული')),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='images/listing')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.district')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.subject')),
            ],
        ),
    ]
