# Generated by Django 5.0.1 on 2024-02-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='listing',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.subject'),
        ),
    ]
