# Generated by Django 5.0.1 on 2024-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
