# Generated by Django 5.0.1 on 2024-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='₾', max_length=1),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
