# Generated by Django 5.0.1 on 2024-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currency',
        ),
    ]
