# Generated by Django 5.0.1 on 2024-02-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.currency'),
        ),
    ]
