# Generated by Django 5.0.1 on 2024-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='_score',
            field=models.IntegerField(default=0),
        ),
    ]
