# Generated by Django 5.0.1 on 2024-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('GEL', '₾'), ('USD', '$')], default='GEL', max_length=3),
        ),
    ]
