# Generated by Django 5.0.1 on 2024-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_unit',
            field=models.CharField(choices=[('hour', 'საათში'), ('month', 'თვეში')], default='hour', max_length=5),
        ),
    ]
